# Generated by Django 4.1.7 on 2023-03-18 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Exam ID')),
                ('exam_topic', models.CharField(max_length=255)),
                ('exam_marks', models.IntegerField()),
                ('user_marks', models.IntegerField()),
                ('exam_time', models.TimeField()),
                ('time_taken', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectiveExamQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Question ID')),
                ('question', models.TextField()),
                ('opt1', models.CharField(max_length=500)),
                ('opt2', models.CharField(max_length=500)),
                ('opt3', models.CharField(max_length=500)),
                ('opt4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examresult')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
