# Generated by Django 4.1.7 on 2023-03-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_examresult_examdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='exam_name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
