# Generated by Django 4.1.7 on 2023-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_examdetails_exam_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='corrected_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examdetails',
            name='no_questions',
            field=models.IntegerField(default=0),
        ),
    ]
