# Generated by Django 4.1.7 on 2023-03-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_examdetails_corrected_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectiveexamquestions',
            name='user_answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
