# Generated by Django 4.1.7 on 2023-03-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_objectiveexamquestions_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='appearence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examdetails',
            name='exam_status',
            field=models.CharField(choices=[('given', 'Given'), ('not-given', 'Not Given')], default='not-given', max_length=255),
        ),
    ]
