# Generated by Django 4.1.7 on 2023-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_objectiveexamquestions_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectiveexamquestions',
            name='user_answer',
            field=models.CharField(default='not-answered', max_length=500),
        ),
    ]
