# Generated by Django 4.1.7 on 2023-03-03 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.UUIDField(default=uuid.UUID('6a6e2ce1-e801-4077-bd09-3c9e70c5879e')),
        ),
    ]
