# Generated by Django 4.1.7 on 2023-03-03 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chatroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.UUIDField(default=uuid.UUID('b0dae31a-3110-476d-a175-3ec4f0b2f52a')),
        ),
    ]
