# Generated by Django 4.1.7 on 2023-03-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequesthistory',
            name='response',
            field=models.TextField(default='generated course'),
        ),
    ]
