# Generated by Django 4.1.7 on 2023-03-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userrequesthistory_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequesthistory',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'User Chat Search History'},
        ),
    ]
