# Generated by Django 4.1.7 on 2023-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
