# Generated by Django 4.1.7 on 2023-03-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_logout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'ThinkInSphere Users'},
        ),
    ]
