# Generated by Django 4.1.7 on 2023-03-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Auth OTP'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_joined'], 'verbose_name_plural': 'Think-In-Sphere User'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'User Profile'},
        ),
    ]
