# Generated by Django 4.1.7 on 2023-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali')], default='en', max_length=255),
        ),
    ]
